name: CD - Entrega Contínua

on:
  push:
    branches: [ "main" ] # Só roda quando o código chega na main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Simulando o Deploy
      run: |
        echo "Iniciando o processo de entrega..."
        echo "Validando pacotes..."
        echo "Aplicação pronta para produção!"